# Generated by Django 4.1.3 on 2022-12-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_remove_employee_department_remove_employee_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='emsapp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='emsapp.post'),
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='district_set', to='emsapp.district'),
        ),
    ]
