# Generated by Django 4.1.3 on 2022-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0003_district_division_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_set', to='emsapp.district'),
        ),
    ]
