# Generated by Django 4.1.3 on 2022-12-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
