# Generated by Django 4.1.3 on 2022-12-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='emsapp.division'),
        ),
    ]
