# Generated by Django 4.1.3 on 2022-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0008_meeting_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='person_with',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
