# Generated by Django 4.1.4 on 2022-12-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0009_meeting_person_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
