# Generated by Django 4.1.4 on 2022-12-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0011_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
