# Generated by Django 4.1.4 on 2022-12-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0012_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
