# Generated by Django 4.1.4 on 2022-12-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0014_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='datetime',
            new_name='attend_date',
        ),
    ]
