# Generated by Django 4.1.4 on 2023-02-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0017_salesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
