# Generated by Django 4.1.4 on 2023-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0018_alter_meeting_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
