# Generated by Django 4.1.4 on 2023-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0019_department_manager_department_start_date_post_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media/images'),
        ),
    ]
