# Generated by Django 3.2.12 on 2023-02-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0020_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_set', to='emsapp.department'),
        ),
    ]
